-- ==============================================================================
-- SAFECHECK FULL DATABASE SCHEMA (CONSOLIDATED SNAPSHOT)
-- Generated automatically from migrations:
--   - 20260907000000_safecheck_initial.sql
--   - 20260908000000_auth_family_schema.sql
--   - 20260909000000_sos_emergency_contacts.sql
--   - 20260910000000_sos_push_schema.sql
--   - 20260910000001_sos_push_helpers.sql
--   - 20260911000000_concurrency_offline_schema.sql
--   - 20260912000000_custom_checkin_schedule.sql
--
-- Dành cho việc Bàn giao (Handoff) hoặc Khởi tạo dự án mới từ con số 0.
-- Không cần phải chạy từng câu lệnh lẻ. Chỉ cần dán toàn bộ file này vào Supabase SQL Editor.
-- ==============================================================================


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- MIGRATION: 20260907000000_safecheck_initial.sql
-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

-- ====================================================================
-- SafeCheck - Migration v1.0: Core Schema, RPC Functions & Cron Jobs
-- ====================================================================

-- 1. Bật Extensions cần thiết
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- 2. Đảm bảo cấu trúc các bảng
CREATE TABLE IF NOT EXISTS configurations (
  family_code VARCHAR PRIMARY KEY,
  checkin_start TIME NOT NULL DEFAULT '07:00:00',
  checkin_deadline TIME NOT NULL DEFAULT '09:00:00',
  emergency_buffer_minutes INT NOT NULL DEFAULT 30,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS checkin_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_code VARCHAR NOT NULL,
  log_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status VARCHAR NOT NULL DEFAULT 'Waiting',
  checkin_time TIMESTAMPTZ,
  source VARCHAR,
  ping_requested_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT unique_family_date UNIQUE (family_code, log_date)
);

-- Thêm cột ping_requested_at nếu bảng đã tồn tại từ trước
ALTER TABLE checkin_logs 
ADD COLUMN IF NOT EXISTS ping_requested_at TIMESTAMPTZ;

-- --------------------------------------------------------------------
-- 3. CÁC HÀM BACKEND RPC (Business Logic)
-- --------------------------------------------------------------------

-- 3.1. Điểm danh hàng ngày (Flow 1 & Flow 4)
CREATE OR REPLACE FUNCTION perform_checkin(p_family_code VARCHAR)
RETURNS JSON AS $$
DECLARE
  v_current_time TIME := CURRENT_TIME;
  v_cfg RECORD;
BEGIN
  SELECT * INTO v_cfg FROM configurations WHERE family_code = p_family_code;
  
  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'message', 'Mã gia đình không tồn tại');
  END IF;

  IF v_current_time < v_cfg.checkin_start THEN
    RETURN json_build_object('success', false, 'message', 'Chưa đến khung giờ điểm danh');
  END IF;

  UPDATE checkin_logs
  SET status = 'Safe',
      checkin_time = now(),
      source = 'Daily_Button'
  WHERE family_code = p_family_code 
    AND log_date = CURRENT_DATE;

  RETURN json_build_object('success', true, 'message', 'Điểm danh an toàn thành công');
END;
$$ LANGUAGE plpgsql;

-- 3.2. Con cháu gửi yêu cầu chuông kiểm tra (Flow 4)
CREATE OR REPLACE FUNCTION request_ping(p_family_code VARCHAR)
RETURNS JSON AS $$
DECLARE
  v_last_ping TIMESTAMPTZ;
BEGIN
  SELECT ping_requested_at INTO v_last_ping
  FROM checkin_logs
  WHERE family_code = p_family_code AND log_date = CURRENT_DATE;

  IF v_last_ping IS NOT NULL AND (now() - v_last_ping) < INTERVAL '15 minutes' THEN
    RETURN json_build_object(
      'success', false, 
      'message', 'Đang trong thời gian chờ (cooldown 15 phút)'
    );
  END IF;

  UPDATE checkin_logs
  SET status = 'Ping_Requested',
      ping_requested_at = now()
  WHERE family_code = p_family_code AND log_date = CURRENT_DATE;

  RETURN json_build_object('success', true, 'message', 'Đã phát chuông kiểm tra tới máy Cụ');
END;
$$ LANGUAGE plpgsql;

-- 3.3. Kích hoạt khẩn cấp SOS (Flow 3)
CREATE OR REPLACE FUNCTION trigger_sos(p_family_code VARCHAR)
RETURNS JSON AS $$
BEGIN
  UPDATE checkin_logs
  SET status = 'Emergency',
      source = 'SOS'
  WHERE family_code = p_family_code AND log_date = CURRENT_DATE;

  RETURN json_build_object('success', true, 'message', 'Đã kích hoạt báo động khẩn cấp');
END;
$$ LANGUAGE plpgsql;

-- 3.4. Con cháu tắt báo động / Xác nhận an toàn (Flow 5)
CREATE OR REPLACE FUNCTION resolve_alarm(p_family_code VARCHAR)
RETURNS JSON AS $$
BEGIN
  UPDATE checkin_logs
  SET status = 'Safe'
  WHERE family_code = p_family_code AND log_date = CURRENT_DATE;

  RETURN json_build_object('success', true, 'message', 'Đã tắt báo động, xác nhận an toàn');
END;
$$ LANGUAGE plpgsql;

-- --------------------------------------------------------------------
-- 4. CÁC HÀM QUÉT ĐỊNH KỲ (Lập lịch với pg_cron)
-- --------------------------------------------------------------------

-- 4.1. Hàm quét trễ giờ, quá hạn, overdue ping
CREATE OR REPLACE FUNCTION check_overdue_routine()
RETURNS VOID AS $$
BEGIN
  -- Quá hạn chốt mà vẫn Waiting -> Chuyển thành Late
  UPDATE checkin_logs log
  SET status = 'Late'
  FROM configurations cfg
  WHERE log.family_code = cfg.family_code
    AND log.log_date = CURRENT_DATE
    AND log.status = 'Waiting'
    AND CURRENT_TIME > cfg.checkin_deadline;

  -- Quá hạn buffer phút sau Late -> Chuyển thành Emergency
  UPDATE checkin_logs log
  SET status = 'Emergency'
  FROM configurations cfg
  WHERE log.family_code = cfg.family_code
    AND log.log_date = CURRENT_DATE
    AND log.status = 'Late'
    AND CURRENT_TIME > (cfg.checkin_deadline + (cfg.emergency_buffer_minutes || ' minutes')::INTERVAL);

  -- Quá 15 phút từ lúc Ping mà Cụ chưa phản hồi -> Chuyển thành Overdue_Ping
  UPDATE checkin_logs
  SET status = 'Overdue_Ping'
  WHERE log_date = CURRENT_DATE
    AND status = 'Ping_Requested'
    AND (now() - ping_requested_at) > INTERVAL '15 minutes';
END;
$$ LANGUAGE plpgsql;

-- 4.2. Hàm tự động reset tạo bản ghi ngày mới lúc 00:00
CREATE OR REPLACE FUNCTION reset_daily_routine()
RETURNS VOID AS $$
BEGIN
  INSERT INTO checkin_logs (family_code, log_date, status)
  SELECT family_code, CURRENT_DATE, 'Waiting'
  FROM configurations
  ON CONFLICT (family_code, log_date) DO NOTHING;
END;
$$ LANGUAGE plpgsql;

-- --------------------------------------------------------------------
-- 5. ĐĂNG KÝ LỊCH CRON JOB (Chỉ đăng ký nếu chưa có)
-- --------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'auto-detect-late-elderly') THEN
    PERFORM cron.schedule(
      'auto-detect-late-elderly',
      '* * * * *',
      'SELECT check_overdue_routine()'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'auto-reset-daily') THEN
    PERFORM cron.schedule(
      'auto-reset-daily',
      '0 0 * * *',
      'SELECT reset_daily_routine()'
    );
  END IF;
END $$;


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- MIGRATION: 20260908000000_auth_family_schema.sql
-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

-- ====================================================================
-- SafeCheck - Migration v2.0: Profiles, Family Links, RLS & Pairing RPC
-- ====================================================================

-- 1. BẢNG PROFILES (Lưu hồ sơ người dùng mở rộng từ auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email VARCHAR(255),
  full_name VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('elderly', 'caregiver')),
  avatar_url TEXT,
  phone VARCHAR(20),
  pairing_code VARCHAR(10) UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Index tìm kiếm nhanh mã ghép nối
CREATE INDEX IF NOT EXISTS idx_profiles_pairing_code ON public.profiles(pairing_code);

-- 2. TRIGGER TỰ ĐỘNG TẠO PROFILE KHI ĐĂNG KÝ (Supabase Auth -> public.profiles)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_role VARCHAR;
  v_pairing_code VARCHAR := NULL;
  v_full_name VARCHAR;
  v_phone VARCHAR;
BEGIN
  -- Lấy role, full_name, phone từ raw_user_meta_data
  v_role := COALESCE(NEW.raw_user_meta_data->>'role', 'elderly');
  v_full_name := COALESCE(NEW.raw_user_meta_data->>'full_name', 'Người dùng');
  v_phone := NEW.raw_user_meta_data->>'phone';

  -- Nếu là Cụ (elderly), tự sinh mã 6 ký tự Base32 trực tiếp, không phụ thuộc hàm ngoài
  IF v_role = 'elderly' THEN
    SELECT string_agg(substr('23456789ABCDEFGHJKMNPQRSTUVWXYZ', floor(random() * 32 + 1)::int, 1), '')
    INTO v_pairing_code
    FROM generate_series(1, 6);
  END IF;

  INSERT INTO public.profiles (id, email, full_name, role, phone, pairing_code)
  VALUES (
    NEW.id,
    NEW.email,
    v_full_name,
    v_role,
    v_phone,
    v_pairing_code
  )
  ON CONFLICT (id) DO UPDATE
  SET email = EXCLUDED.email,
      full_name = EXCLUDED.full_name,
      role = EXCLUDED.role,
      phone = EXCLUDED.phone,
      pairing_code = COALESCE(public.profiles.pairing_code, EXCLUDED.pairing_code);

  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'Lỗi trong handle_new_user: %', SQLERRM;
  RETURN NEW;
END;
$$;

-- Gắn Trigger vào bảng auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 4. TRIGGER CHẶN TỰ Ý SỬA ROLE (Chống Privilege Escalation)
CREATE OR REPLACE FUNCTION public.prevent_role_change()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.role IS DISTINCT FROM NEW.role THEN
    RAISE EXCEPTION 'Bảo mật: Không được phép tự ý thay đổi vai trò (role)!';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_prevent_role_change ON public.profiles;
CREATE TRIGGER tr_prevent_role_change
BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.prevent_role_change();

-- 5. BẢNG FAMILY_LINKS (Quan hệ 1 Cụ - Nhiều Con Cháu)
CREATE TABLE IF NOT EXISTS public.family_links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  elderly_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  caregiver_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  relationship VARCHAR(50) DEFAULT 'Người thân',
  status VARCHAR(20) NOT NULL DEFAULT 'accepted' CHECK (status IN ('accepted', 'pending', 'revoked')),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  
  -- Ràng buộc 1: Chống kết nối trùng lặp
  CONSTRAINT unique_elderly_caregiver UNIQUE (elderly_id, caregiver_id),
  
  -- Ràng buộc 2: Chống tự liên kết với chính mình
  CONSTRAINT check_not_self_link CHECK (elderly_id <> caregiver_id)
);

CREATE INDEX IF NOT EXISTS idx_family_links_caregiver ON public.family_links(caregiver_id);
CREATE INDEX IF NOT EXISTS idx_family_links_elderly ON public.family_links(elderly_id);

-- Bổ sung cột elderly_id vào bảng checkin_logs để gắn trực tiếp theo Cụ
ALTER TABLE public.checkin_logs
ADD COLUMN IF NOT EXISTS elderly_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_checkin_logs_elderly_date ON public.checkin_logs(elderly_id, log_date);

-- --------------------------------------------------------------------
-- 6. ROW LEVEL SECURITY (RLS) - BẢO VỆ DỮ LIỆU CẤP HÀNG
-- --------------------------------------------------------------------

-- 6.1. RLS trên bảng PROFILES
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Ai cũng đọc được profile của chính mình
CREATE POLICY "Users can view own profile"
ON public.profiles FOR SELECT
USING (auth.uid() = id);

-- Caregiver được đọc profile của Cụ mà mình ĐÃ LIÊN KẾT (accepted)
CREATE POLICY "Caregivers can view linked elderly profile"
ON public.profiles FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.family_links
    WHERE family_links.caregiver_id = auth.uid()
      AND family_links.elderly_id = public.profiles.id
      AND family_links.status = 'accepted'
  )
);

-- Cụ được đọc profile của những Con cháu đang theo dõi mình
CREATE POLICY "Elderly can view linked caregivers"
ON public.profiles FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.family_links
    WHERE family_links.elderly_id = auth.uid()
      AND family_links.caregiver_id = public.profiles.id
      AND family_links.status = 'accepted'
  )
);

-- Người dùng chỉ được sửa thông tin cá nhân của chính mình (Tên, Avatar, Phone)
CREATE POLICY "Users can update own profile"
ON public.profiles FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- 6.2. RLS trên bảng FAMILY_LINKS
ALTER TABLE public.family_links ENABLE ROW LEVEL SECURITY;

-- Cụ hoặc Con cháu đều đọc được các link liên quan đến mình
CREATE POLICY "Users can view own family links"
ON public.family_links FOR SELECT
USING (auth.uid() = elderly_id OR auth.uid() = caregiver_id);

-- Cụ hoặc Con cháu có quyền xóa / hủy link của mình
CREATE POLICY "Users can delete own family links"
ON public.family_links FOR DELETE
USING (auth.uid() = elderly_id OR auth.uid() = caregiver_id);

-- 6.3. RLS trên bảng CHECKIN_LOGS
ALTER TABLE public.checkin_logs ENABLE ROW LEVEL SECURITY;

-- Cụ đọc được lịch sử của chính mình qua pairing_code
DROP POLICY IF EXISTS "Elderly view own checkin logs" ON public.checkin_logs;
CREATE POLICY "Elderly view own checkin logs"
ON public.checkin_logs FOR SELECT
USING (
  family_code IN (
    SELECT pairing_code FROM public.profiles WHERE id = auth.uid()
  )
);

-- Con cháu chỉ đọc được lịch sử của Cụ ĐÃ LIÊN KẾT
DROP POLICY IF EXISTS "Caregivers view linked elderly checkin logs" ON public.checkin_logs;
CREATE POLICY "Caregivers view linked elderly checkin logs"
ON public.checkin_logs FOR SELECT
USING (
  family_code IN (
    SELECT p.pairing_code 
    FROM public.profiles p
    JOIN public.family_links fl ON fl.elderly_id = p.id
    WHERE fl.caregiver_id = auth.uid()
      AND fl.status = 'accepted'
  )
);

-- --------------------------------------------------------------------
-- 7. RPC GHÉP NỐI GIA ĐÌNH (connect_family)
-- --------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.connect_family(
  p_pairing_code VARCHAR,
  p_relationship VARCHAR DEFAULT 'Người thân'
)
RETURNS JSON 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = public, auth
AS $$
DECLARE
  v_caregiver_id UUID := auth.uid();
  v_caregiver_role VARCHAR;
  v_elderly RECORD;
  v_clean_code VARCHAR;
BEGIN
  -- 1. Kiểm tra phiên đăng nhập
  IF v_caregiver_id IS NULL THEN
    RETURN json_build_object('success', false, 'message', 'Bạn chưa đăng nhập');
  END IF;

  -- 2. Kiểm tra vai trò của người gọi (phải là caregiver)
  SELECT role INTO v_caregiver_role FROM public.profiles WHERE id = v_caregiver_id;
  IF v_caregiver_role <> 'caregiver' THEN
    RETURN json_build_object('success', false, 'message', 'Chỉ tài khoản Người thân (Caregiver) mới có thể kết nối với Cụ');
  END IF;

  -- 3. Chuẩn hóa mã (Viết hoa, bỏ khoảng trắng)
  v_clean_code := UPPER(TRIM(p_pairing_code));
  IF length(v_clean_code) < 6 THEN
    RETURN json_build_object('success', false, 'message', 'Mã ghép nối phải gồm 6 ký tự');
  END IF;

  -- 4. Tìm kiếm Cụ sở hữu mã này
  SELECT id, full_name, avatar_url INTO v_elderly
  FROM public.profiles
  WHERE pairing_code = v_clean_code AND role = 'elderly';

  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'message', 'Mã kết nối không chính xác hoặc không tồn tại');
  END IF;

  -- 5. Chặn tự kết nối chính mình (nếu có lỗi dữ liệu)
  IF v_elderly.id = v_caregiver_id THEN
    RETURN json_build_object('success', false, 'message', 'Không thể tự kết nối với chính mình');
  END IF;

  -- 6. Tạo hoặc cập nhật liên kết trong family_links
  INSERT INTO public.family_links (elderly_id, caregiver_id, relationship, status)
  VALUES (v_elderly.id, v_caregiver_id, COALESCE(p_relationship, 'Người thân'), 'accepted')
  ON CONFLICT (elderly_id, caregiver_id) 
  DO UPDATE SET status = 'accepted', relationship = EXCLUDED.relationship, updated_at = now();

  RETURN json_build_object(
    'success', true,
    'message', 'Đã kết nối thành công với ' || v_elderly.full_name,
    'elderly_id', v_elderly.id,
    'elderly_name', v_elderly.full_name,
    'avatar_url', v_elderly.avatar_url
  );
END;
$$;

-- --------------------------------------------------------------------
-- 8. CẬP NHẬT CÁC HÀM NGHIỆP VỤ ĐA GIA ĐÌNH / MÃ GHÉP NỐI ĐỘNG
-- --------------------------------------------------------------------

-- 8.0. Gỡ bỏ ràng buộc khóa ngoại cũ sang configurations để checkin_logs hoạt động độc lập
ALTER TABLE public.checkin_logs DROP CONSTRAINT IF EXISTS checkin_logs_family_code_fkey;

-- 8.1. Điểm danh: Ghi trực tiếp trạng thái Safe vào checkin_logs cho mã Cụ
CREATE OR REPLACE FUNCTION public.perform_checkin(p_family_code VARCHAR)
RETURNS JSON 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = public, auth
AS $$
DECLARE
  v_clean_code VARCHAR := UPPER(TRIM(p_family_code));
BEGIN
  INSERT INTO public.checkin_logs (family_code, log_date, status, checkin_time, source)
  VALUES (v_clean_code, CURRENT_DATE, 'Safe', now(), 'Daily_Button')
  ON CONFLICT (family_code, log_date)
  DO UPDATE SET status = 'Safe', checkin_time = now(), source = 'Daily_Button';

  RETURN json_build_object('success', true, 'message', 'Điểm danh an toàn thành công');
END;
$$;

-- 8.2. Kích hoạt SOS cho từng Cụ
CREATE OR REPLACE FUNCTION public.trigger_sos(p_family_code VARCHAR)
RETURNS JSON 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = public, auth
AS $$
DECLARE
  v_clean_code VARCHAR := UPPER(TRIM(p_family_code));
BEGIN
  INSERT INTO public.checkin_logs (family_code, log_date, status, source)
  VALUES (v_clean_code, CURRENT_DATE, 'Emergency', 'SOS')
  ON CONFLICT (family_code, log_date)
  DO UPDATE SET status = 'Emergency', source = 'SOS';

  RETURN json_build_object('success', true, 'message', 'Đã kích hoạt báo động khẩn cấp');
END;
$$;

-- 8.3. Gửi chuông kiểm tra (Ping)
CREATE OR REPLACE FUNCTION public.request_ping(p_family_code VARCHAR)
RETURNS JSON 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = public, auth
AS $$
DECLARE
  v_clean_code VARCHAR := UPPER(TRIM(p_family_code));
  v_last_ping TIMESTAMPTZ;
  v_caller_email VARCHAR;
  v_cooldown_interval INTERVAL := INTERVAL '15 minutes';
BEGIN
  -- Nếu người gọi là tester test01@gmail.com: giảm thời gian chờ xuống 10 giây để kiểm thử
  SELECT email INTO v_caller_email FROM public.profiles WHERE id = auth.uid();
  IF LOWER(v_caller_email) = 'test01@gmail.com' THEN
    v_cooldown_interval := INTERVAL '10 seconds';
  END IF;

  SELECT ping_requested_at INTO v_last_ping
  FROM public.checkin_logs
  WHERE family_code = v_clean_code AND log_date = CURRENT_DATE;

  IF v_last_ping IS NOT NULL AND (now() - v_last_ping) < v_cooldown_interval THEN
    RETURN json_build_object(
      'success', false, 
      'message', 'Đang trong thời gian chờ (cooldown ' || 
        CASE WHEN LOWER(v_caller_email) = 'test01@gmail.com' THEN '10 giây' ELSE '15 phút' END || ')'
    );
  END IF;

  INSERT INTO public.checkin_logs (family_code, log_date, status, ping_requested_at)
  VALUES (v_clean_code, CURRENT_DATE, 'Ping_Requested', now())
  ON CONFLICT (family_code, log_date)
  DO UPDATE SET status = 'Ping_Requested', ping_requested_at = now();

  RETURN json_build_object('success', true, 'message', 'Đã phát chuông kiểm tra tới máy Cụ');
END;
$$;

-- 8.4. Tắt báo động / Xác nhận an toàn
CREATE OR REPLACE FUNCTION public.resolve_alarm(p_family_code VARCHAR)
RETURNS JSON 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = public, auth
AS $$
DECLARE
  v_clean_code VARCHAR := UPPER(TRIM(p_family_code));
BEGIN
  INSERT INTO public.checkin_logs (family_code, log_date, status)
  VALUES (v_clean_code, CURRENT_DATE, 'Safe')
  ON CONFLICT (family_code, log_date)
  DO UPDATE SET status = 'Safe';

  RETURN json_build_object('success', true, 'message', 'Đã tắt báo động, xác nhận an toàn');
END;
$$;

-- 8.5. Cấp quyền thực thi (GRANT EXECUTE) cho authenticated và anon
GRANT EXECUTE ON FUNCTION public.connect_family(VARCHAR, VARCHAR) TO authenticated;
GRANT EXECUTE ON FUNCTION public.perform_checkin(VARCHAR) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.trigger_sos(VARCHAR) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.request_ping(VARCHAR) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.resolve_alarm(VARCHAR) TO authenticated, anon;




-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- MIGRATION: 20260909000000_sos_emergency_contacts.sql
-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

-- ====================================================================
-- SafeCheck - Migration v3.0: SOS Emergency Contacts, Triggers & RLS
-- ====================================================================

-- 1. BẢNG EMERGENCY_CONTACTS (Danh bạ cứu hộ khẩn cấp cho người cao tuổi)
CREATE TABLE IF NOT EXISTS public.emergency_contacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  elderly_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  contact_type VARCHAR(20) NOT NULL CHECK (contact_type IN ('neighbor', 'relative', 'authority', 'medical', 'other')),
  note VARCHAR(255),
  priority_order INT NOT NULL CHECK (priority_order BETWEEN 1 AND 5),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),

  -- Ràng buộc thứ tự ưu tiên duy nhất cho mỗi Cụ (hoãn kiểm tra cuối lệnh để hỗ trợ đổi vị trí)
  CONSTRAINT uq_elderly_priority UNIQUE (elderly_id, priority_order) DEFERRABLE INITIALLY DEFERRED
);

-- Index tra cứu danh bạ khẩn cấp theo Cụ và sắp xếp theo độ ưu tiên
CREATE INDEX IF NOT EXISTS idx_emergency_contacts_elderly 
ON public.emergency_contacts(elderly_id, priority_order ASC);

-- --------------------------------------------------------------------
-- 2. TRIGGERS BẢO VỆ DỮ LIỆU & QUY TẮC NGHIỆP VỤ
-- --------------------------------------------------------------------

-- Trigger 1: Khóa cứng elderly_id (Immutable - Chống tráo đổi danh bạ giữa các Cụ)
CREATE OR REPLACE FUNCTION public.prevent_elderly_id_change()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.elderly_id IS DISTINCT FROM NEW.elderly_id THEN
    RAISE EXCEPTION 'Bảo mật: Không được phép thay đổi elderly_id của liên hệ khẩn cấp!';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_prevent_elderly_id_change ON public.emergency_contacts;
CREATE TRIGGER tr_prevent_elderly_id_change
BEFORE UPDATE ON public.emergency_contacts
FOR EACH ROW EXECUTE FUNCTION public.prevent_elderly_id_change();

-- Trigger 2: Chặn vượt quá 5 liên hệ cho mỗi Cụ (Chỉ kiểm tra khi INSERT mới)
CREATE OR REPLACE FUNCTION public.check_emergency_contacts_limit()
RETURNS TRIGGER AS $$
BEGIN
  IF (SELECT COUNT(*) FROM public.emergency_contacts WHERE elderly_id = NEW.elderly_id) >= 5 THEN
    RAISE EXCEPTION 'Nghiệp vụ SafeCheck: Mỗi Cụ chỉ được lưu tối đa 5 liên hệ cứu hộ khẩn cấp!';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_check_emergency_contacts_limit ON public.emergency_contacts;
CREATE TRIGGER tr_check_emergency_contacts_limit
BEFORE INSERT ON public.emergency_contacts
FOR EACH ROW EXECUTE FUNCTION public.check_emergency_contacts_limit();

-- Trigger 3: Tự động chuẩn hóa lại thứ tự ưu tiên (Priority Normalization) sau khi XÓA
CREATE OR REPLACE FUNCTION public.normalize_emergency_contacts_priority()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.emergency_contacts
  SET priority_order = sub.new_order,
      updated_at = timezone('utc'::text, now())
  FROM (
    SELECT id, ROW_NUMBER() OVER (ORDER BY priority_order ASC, created_at ASC) as new_order
    FROM public.emergency_contacts
    WHERE elderly_id = OLD.elderly_id
  ) sub
  WHERE public.emergency_contacts.id = sub.id
    AND public.emergency_contacts.priority_order <> sub.new_order;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_normalize_priority_after_delete ON public.emergency_contacts;
CREATE TRIGGER tr_normalize_priority_after_delete
AFTER DELETE ON public.emergency_contacts
FOR EACH ROW EXECUTE FUNCTION public.normalize_emergency_contacts_priority();

-- --------------------------------------------------------------------
-- 3. ROW LEVEL SECURITY (RLS) - BẢO MẬT PHÂN QUYỀN ĐA TẦNG
-- --------------------------------------------------------------------
ALTER TABLE public.emergency_contacts ENABLE ROW LEVEL SECURITY;

-- 3.1. SELECT: Cụ xem của mình, Con cháu xem của Cụ đã liên kết hợp lệ (status = 'accepted')
DROP POLICY IF EXISTS "View emergency contacts" ON public.emergency_contacts;
CREATE POLICY "View emergency contacts"
ON public.emergency_contacts FOR SELECT
USING (
  elderly_id = auth.uid()
  OR EXISTS (
    SELECT 1 FROM public.family_links fl
    WHERE fl.elderly_id = emergency_contacts.elderly_id
      AND fl.caregiver_id = auth.uid()
      AND fl.status = 'accepted'
  )
);

-- 3.2. INSERT: Chỉ Con cháu đã liên kết mới được tạo liên hệ cho Cụ đó
DROP POLICY IF EXISTS "Caregiver insert emergency contacts" ON public.emergency_contacts;
CREATE POLICY "Caregiver insert emergency contacts"
ON public.emergency_contacts FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.family_links fl
    WHERE fl.elderly_id = emergency_contacts.elderly_id
      AND fl.caregiver_id = auth.uid()
      AND fl.status = 'accepted'
  )
);

-- 3.3. UPDATE: Chỉ Con cháu đã liên kết mới được cập nhật liên hệ của Cụ
DROP POLICY IF EXISTS "Caregiver update emergency contacts" ON public.emergency_contacts;
CREATE POLICY "Caregiver update emergency contacts"
ON public.emergency_contacts FOR UPDATE
USING (
  EXISTS (
    SELECT 1 FROM public.family_links fl
    WHERE fl.elderly_id = emergency_contacts.elderly_id
      AND fl.caregiver_id = auth.uid()
      AND fl.status = 'accepted'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.family_links fl
    WHERE fl.elderly_id = emergency_contacts.elderly_id
      AND fl.caregiver_id = auth.uid()
      AND fl.status = 'accepted'
  )
);

-- 3.4. DELETE: Chỉ Con cháu đã liên kết mới được xóa liên hệ
DROP POLICY IF EXISTS "Caregiver delete emergency contacts" ON public.emergency_contacts;
CREATE POLICY "Caregiver delete emergency contacts"
ON public.emergency_contacts FOR DELETE
USING (
  EXISTS (
    SELECT 1 FROM public.family_links fl
    WHERE fl.elderly_id = emergency_contacts.elderly_id
      AND fl.caregiver_id = auth.uid()
      AND fl.status = 'accepted'
  )
);


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- MIGRATION: 20260910000000_sos_push_schema.sql
-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

-- ==============================================================================
-- Migration: 20260910000000_sos_push_schema.sql
-- Mô tả: Khởi tạo bảng sos_events (Source of Truth) và push_subscriptions
--        cho hệ thống Web Push Notifications ngoại tuyến của SafeCheck.
-- Tuân thủ: PRD_NotiSOS.md & implementation_plan.md
-- ==============================================================================

-- 1. BẢNG SỰ KIỆN SOS KHẨN CẤP (sos_events - SOURCE OF TRUTH)
CREATE TABLE IF NOT EXISTS public.sos_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    elderly_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'resolved', 'cancelled')),
    trigger_source TEXT NOT NULL DEFAULT 'button' CHECK (trigger_source IN ('button', 'timeout', 'fall_detection')),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    address TEXT,
    push_dispatched_at TIMESTAMPTZ,
    push_dispatched_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    resolved_at TIMESTAMPTZ,
    resolved_by UUID REFERENCES public.profiles(id)
);

CREATE INDEX IF NOT EXISTS idx_sos_events_elderly ON public.sos_events(elderly_id);
CREATE INDEX IF NOT EXISTS idx_sos_events_status ON public.sos_events(status);

-- 2. BẢNG LƯU TRỮ WEB PUSH SUBSCRIPTIONS (push_subscriptions)
CREATE TABLE IF NOT EXISTS public.push_subscriptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    endpoint TEXT NOT NULL UNIQUE,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    platform TEXT NOT NULL DEFAULT 'unknown' CHECK (platform IN ('ios', 'android', 'desktop', 'unknown')),
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user ON public.push_subscriptions(user_id);

-- 3. THIẾT LẬP ROW LEVEL SECURITY (RLS)
ALTER TABLE public.sos_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

-- 3.1. RLS cho sos_events:
-- Elderly INSERT chính sự kiện của mình
DROP POLICY IF EXISTS "Elderly can insert own sos_events" ON public.sos_events;
CREATE POLICY "Elderly can insert own sos_events"
    ON public.sos_events FOR INSERT
    WITH CHECK (auth.uid() = elderly_id);

-- Elderly và linked Caregivers (status = 'accepted') có quyền SELECT
DROP POLICY IF EXISTS "Elderly and linked caregivers can view sos_events" ON public.sos_events;
CREATE POLICY "Elderly and linked caregivers can view sos_events"
    ON public.sos_events FOR SELECT
    USING (
        auth.uid() = elderly_id OR
        EXISTS (
            SELECT 1 FROM public.family_links fl
            WHERE fl.elderly_id = sos_events.elderly_id
              AND fl.caregiver_id = auth.uid()
              AND fl.status = 'accepted'
        )
    );

-- Caregiver CHỈ được phép UPDATE khi status = 'active', chỉ đổi status = 'resolved' và resolved_by = auth.uid()
DROP POLICY IF EXISTS "Linked caregivers can resolve active sos_events" ON public.sos_events;
CREATE POLICY "Linked caregivers can resolve active sos_events"
    ON public.sos_events FOR UPDATE
    USING (
        status = 'active' AND
        EXISTS (
            SELECT 1 FROM public.family_links fl
            WHERE fl.elderly_id = sos_events.elderly_id
              AND fl.caregiver_id = auth.uid()
              AND fl.status = 'accepted'
        )
    )
    WITH CHECK (
        status = 'resolved' AND
        resolved_by = auth.uid()
    );

-- 3.2. RLS cho push_subscriptions:
-- Chỉ người sở hữu mới được SELECT / INSERT / UPDATE / DELETE subscription của chính mình.
-- Tuyệt đối không cho phép thành viên khác xem endpoint (Secret Capability URL).
DROP POLICY IF EXISTS "Users can manage own subscriptions" ON public.push_subscriptions;
CREATE POLICY "Users can manage own subscriptions"
    ON public.push_subscriptions FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- MIGRATION: 20260910000001_sos_push_helpers.sql
-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

-- ==============================================================================
-- Migration: 20260910000001_sos_push_helpers.sql
-- Mô tả: Thêm các RPC functions SECURITY DEFINER để phục vụ Web Push Dispatcher
--        hoạt động độc lập, không phụ thuộc vào SERVICE_ROLE_KEY trên Vercel.
-- ==============================================================================

-- 1. Hàm nguyên tử khóa và xác thực quyền gửi push (Atomic Idempotency Claim)
CREATE OR REPLACE FUNCTION public.claim_sos_push_dispatch(
    p_sos_event_id UUID,
    p_caller_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_event RECORD;
    v_claimed BOOLEAN := FALSE;
    v_elderly_name TEXT;
BEGIN
    -- Lấy thông tin sự kiện
    SELECT * INTO v_event FROM public.sos_events WHERE id = p_sos_event_id;
    
    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'SOS event not found');
    END IF;
    
    -- Kiểm tra người gọi phải là Cụ bà sở hữu sự kiện, hoặc con cháu đã liên kết (hỗ trợ test)
    IF v_event.elderly_id != p_caller_id AND NOT EXISTS (
        SELECT 1 FROM public.family_links 
        WHERE elderly_id = v_event.elderly_id 
          AND caregiver_id = p_caller_id 
          AND status = 'accepted'
    ) THEN
        RETURN jsonb_build_object('success', false, 'error', 'Forbidden: Caller is not authorized for this SOS event');
    END IF;
    
    -- Lấy tên Cụ bà
    SELECT full_name INTO v_elderly_name FROM public.profiles WHERE id = v_event.elderly_id;
    IF v_elderly_name IS NULL OR v_elderly_name = '' THEN
        v_elderly_name := 'Người thân';
    END IF;

    -- Khóa nguyên tử: Đánh dấu đã dispatch nếu chưa từng dispatch
    UPDATE public.sos_events
    SET push_dispatched_at = now(),
        push_dispatched_count = push_dispatched_count + 1
    WHERE id = p_sos_event_id
      AND push_dispatched_at IS NULL;
      
    IF FOUND THEN
        v_claimed := TRUE;
    END IF;
    
    RETURN jsonb_build_object(
        'success', true, 
        'claimed', v_claimed, 
        'elderly_id', v_event.elderly_id,
        'elderly_name', v_elderly_name
    );
END;
$$;

-- 2. Hàm lấy danh sách subscriptions của con cháu đã liên kết với Cụ bà
CREATE OR REPLACE FUNCTION public.get_caregiver_push_subscriptions(
    p_elderly_id UUID
)
RETURNS TABLE (
    endpoint TEXT,
    p256dh TEXT,
    auth TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT ps.endpoint, ps.p256dh, ps.auth
    FROM public.push_subscriptions ps
    JOIN public.family_links fl ON fl.caregiver_id = ps.user_id
    WHERE fl.elderly_id = p_elderly_id
      AND fl.status = 'accepted';
END;
$$;

-- 3. Hàm tạo sự kiện SOS an toàn cho Cụ bà hoặc Con cháu đã liên kết (hỗ trợ Dev Tool và test chéo)
CREATE OR REPLACE FUNCTION public.create_sos_event(
    p_elderly_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_caller_id UUID := auth.uid();
    v_new_id UUID;
    v_pairing_code VARCHAR;
BEGIN
    IF v_caller_id != p_elderly_id AND NOT EXISTS (
        SELECT 1 FROM public.family_links 
        WHERE elderly_id = p_elderly_id 
          AND caregiver_id = v_caller_id 
          AND status = 'accepted'
    ) THEN
        RETURN jsonb_build_object('success', false, 'error', 'Forbidden: Caller not authorized');
    END IF;

    SELECT pairing_code INTO v_pairing_code FROM public.profiles WHERE id = p_elderly_id;
    IF v_pairing_code IS NOT NULL THEN
        INSERT INTO public.checkin_logs (family_code, log_date, status, source)
        VALUES (v_pairing_code, CURRENT_DATE, 'Emergency', 'SOS')
        ON CONFLICT (family_code, log_date)
        DO UPDATE SET status = 'Emergency', source = 'SOS';
    END IF;

    INSERT INTO public.sos_events (elderly_id, status, trigger_source)
    VALUES (p_elderly_id, 'active', 'button')
    RETURNING id INTO v_new_id;

    RETURN jsonb_build_object('success', true, 'sos_event_id', v_new_id);
END;
$$;

-- 4. Cập nhật RLS Policy để cho phép cả Cụ bà và Con cháu đã liên kết INSERT / SELECT vào sos_events
DROP POLICY IF EXISTS "Elderly can insert own sos_events" ON public.sos_events;
DROP POLICY IF EXISTS "Elderly and linked caregivers can insert sos_events" ON public.sos_events;
CREATE POLICY "Elderly and linked caregivers can insert sos_events"
    ON public.sos_events FOR INSERT
    WITH CHECK (
        auth.uid() = elderly_id OR
        EXISTS (
            SELECT 1 FROM public.family_links
            WHERE elderly_id = sos_events.elderly_id
              AND caregiver_id = auth.uid()
              AND status = 'accepted'
        )
    );

-- 5. Hàm dọn dẹp subscription hết hạn (Housekeeping)
CREATE OR REPLACE FUNCTION public.remove_expired_push_subscriptions(
    p_endpoints TEXT[]
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    DELETE FROM public.push_subscriptions
    WHERE endpoint = ANY(p_endpoints);
END;
$$;


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- MIGRATION: 20260911000000_concurrency_offline_schema.sql
-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

-- ==============================================================================
-- SafeCheck - Migration: 20260911000000_concurrency_offline_schema.sql
-- Mô tả: Cung cấp cơ chế Concurrency Control (Atomic Resolve & Ping qua Row Lock)
--        và Offline Resilience (Idempotent SOS Insert + Audit Trail bất biến).
-- Tuân thủ: PRD_Deep_v1.md (v3.0) & implementation_plan.md
-- ==============================================================================

-- 1. BỔ SUNG IDEMPOTENCY KEY VÀO BẢNG SOS_EVENTS
ALTER TABLE public.sos_events
ADD COLUMN IF NOT EXISTS client_event_id UUID UNIQUE,
ADD COLUMN IF NOT EXISTS resolution_note TEXT;

CREATE INDEX IF NOT EXISTS idx_sos_events_client_id ON public.sos_events(client_event_id);

-- 2. BẢNG ALARM_LOGS (AUDIT TRAIL BẢO MẬT TỐI GIẢN - DATA MINIMIZATION)
-- Tuyệt đối KHÔNG lưu pairing_code trong bảng này
CREATE TABLE IF NOT EXISTS public.alarm_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    elderly_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    sos_event_id UUID REFERENCES public.sos_events(id) ON DELETE SET NULL,
    action VARCHAR(30) NOT NULL CHECK (action IN ('SOS_TRIGGERED', 'RESOLVE', 'PING', 'CHECKIN_SAFE')),
    performed_by UUID NOT NULL REFERENCES public.profiles(id),
    performer_name VARCHAR(100) NOT NULL,
    performer_role VARCHAR(20) NOT NULL,
    note TEXT,
    previous_state VARCHAR(30),
    new_state VARCHAR(30),
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_alarm_logs_elderly ON public.alarm_logs(elderly_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alarm_logs_sos_event ON public.alarm_logs(sos_event_id);

-- Thiết lập Row Level Security (RLS) trên alarm_logs
ALTER TABLE public.alarm_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view relevant alarm logs" ON public.alarm_logs;
CREATE POLICY "Users can view relevant alarm logs"
ON public.alarm_logs FOR SELECT
USING (
  auth.uid() = elderly_id OR
  EXISTS (
    SELECT 1 FROM public.family_links fl
    WHERE fl.elderly_id = alarm_logs.elderly_id
      AND fl.caregiver_id = auth.uid()
      AND fl.status = 'accepted'
  )
);

-- 3. RPC FUNCTION: create_sos_event_idempotent
-- Tạo sự kiện SOS nguyên tử với Idempotency Key, chống race condition khi client retry
CREATE OR REPLACE FUNCTION public.create_sos_event_idempotent(
  p_elderly_id UUID,
  p_client_event_id UUID,
  p_trigger_source TEXT DEFAULT 'button'
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_caller_id UUID := auth.uid();
  v_existing_event RECORD;
  v_new_event RECORD;
  v_pairing_code VARCHAR;
  v_caller_name VARCHAR;
  v_caller_role VARCHAR;
BEGIN
  -- 1. Bảo mật: Chặn đứng Anonymous Caller
  IF v_caller_id IS NULL THEN
    RAISE EXCEPTION 'Unauthorized: Yêu cầu đăng nhập để thực hiện tác vụ này' USING ERRCODE = '42501';
  END IF;

  -- 2. Xác thực quyền: Người gọi phải là Cụ hoặc con cháu đã liên kết accepted
  IF v_caller_id <> p_elderly_id AND NOT EXISTS (
    SELECT 1 FROM public.family_links
    WHERE elderly_id = p_elderly_id 
      AND caregiver_id = v_caller_id 
      AND status = 'accepted'
  ) THEN
    RAISE EXCEPTION 'Forbidden: Bạn không có quyền kích hoạt báo động cho người dùng này' USING ERRCODE = '42501';
  END IF;

  -- 3. INSERT NGUYÊN TỬ VỚI ON CONFLICT (Triệt tiêu hoàn toàn race condition dạng SELECT -> INSERT)
  INSERT INTO public.sos_events (
    elderly_id, client_event_id, status, trigger_source
  ) VALUES (
    p_elderly_id, p_client_event_id, 'active', COALESCE(p_trigger_source, 'button')
  )
  ON CONFLICT (client_event_id) DO NOTHING
  RETURNING * INTO v_new_event;

  -- Nếu không có dòng nào được insert -> Request này là Duplicate/Retry do xung đột đồng thời
  IF v_new_event.id IS NULL THEN
    SELECT id, status, created_at INTO v_existing_event
    FROM public.sos_events
    WHERE client_event_id = p_client_event_id;

    RETURN jsonb_build_object(
      'success', true,
      'sos_event_id', v_existing_event.id,
      'status', v_existing_event.status,
      'is_duplicate', true,
      'message', 'Sự kiện đã được ghi nhận trước đó (Idempotent ACK)'
    );
  END IF;

  -- 4. Đọc pairing_code và profile để phản chiếu trạng thái
  SELECT pairing_code INTO v_pairing_code FROM public.profiles WHERE id = p_elderly_id;
  SELECT full_name, role INTO v_caller_name, v_caller_role FROM public.profiles WHERE id = v_caller_id;

  -- Phản chiếu trạng thái sang checkin_logs hôm nay
  IF v_pairing_code IS NOT NULL THEN
    INSERT INTO public.checkin_logs (family_code, log_date, status, source)
    VALUES (v_pairing_code, CURRENT_DATE, 'Emergency', 'SOS')
    ON CONFLICT (family_code, log_date)
    DO UPDATE SET status = 'Emergency', source = 'SOS';
  END IF;

  -- 5. Ghi Audit Log trong cùng transaction (Tuyệt đối không lưu pairing_code)
  INSERT INTO public.alarm_logs (
    elderly_id, sos_event_id, action,
    performed_by, performer_name, performer_role, new_state
  ) VALUES (
    p_elderly_id, v_new_event.id, 'SOS_TRIGGERED',
    v_caller_id, COALESCE(v_caller_name, 'Người dùng'), COALESCE(v_caller_role, 'elderly'), 'Emergency'
  );

  RETURN jsonb_build_object(
    'success', true,
    'sos_event_id', v_new_event.id,
    'status', 'active',
    'is_duplicate', false,
    'message', 'Đã kích hoạt sự kiện cứu hộ thành công'
  );
END;
$$;

-- 4. RPC FUNCTION: resolve_alarm_atomic
-- Tắt báo động nguyên tử qua khóa hàng sos_events FOR UPDATE, bắt buộc p_sos_event_id
CREATE OR REPLACE FUNCTION public.resolve_alarm_atomic(
  p_elderly_id UUID,
  p_sos_event_id UUID,
  p_note TEXT DEFAULT 'Xác nhận an toàn từ ứng dụng'
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_caller_id UUID := auth.uid();
  v_caller_name VARCHAR(100);
  v_caller_role VARCHAR(20);
  v_pairing_code VARCHAR;
  v_target_sos RECORD;
  v_last_resolver_name VARCHAR;
  v_last_resolved_at TIMESTAMPTZ;
BEGIN
  -- 1. Bảo mật: Chặn đứng Anonymous Caller
  IF v_caller_id IS NULL THEN
    RAISE EXCEPTION 'Unauthorized: Yêu cầu đăng nhập để thực hiện tác vụ này' USING ERRCODE = '42501';
  END IF;

  -- 2. Kiểm tra tham số bắt buộc (Production path: bắt buộc có sos_event_id)
  IF p_sos_event_id IS NULL THEN
    RAISE EXCEPTION 'Bad Request: Yêu cầu cung cấp p_sos_event_id cần giải quyết' USING ERRCODE = '22023';
  END IF;

  -- 3. Xác thực quan hệ gia đình (Caregiver phải có link accepted hoặc chính Cụ)
  IF v_caller_id <> p_elderly_id AND NOT EXISTS (
    SELECT 1 FROM public.family_links
    WHERE elderly_id = p_elderly_id 
      AND caregiver_id = v_caller_id 
      AND status = 'accepted'
  ) THEN
    RAISE EXCEPTION 'Forbidden: Bạn không có quyền giải quyết báo động của người dùng này' USING ERRCODE = '42501';
  END IF;

  -- 4. Lấy thông tin người thực hiện & pairing_code của Cụ
  SELECT full_name, role INTO v_caller_name, v_caller_role FROM public.profiles WHERE id = v_caller_id;
  SELECT pairing_code INTO v_pairing_code FROM public.profiles WHERE id = p_elderly_id;

  -- 5. KHÓA ĐÍCH DANH HÀNG SOS_EVENTS ĐƯỢC CHỈ ĐỊNH (Source of Truth)
  SELECT * INTO v_target_sos
  FROM public.sos_events
  WHERE id = p_sos_event_id AND elderly_id = p_elderly_id
  FOR UPDATE;

  -- 6. Xử lý trường hợp xung đột: Sự kiện không tồn tại hoặc đã được resolve trước đó
  IF v_target_sos.id IS NULL OR v_target_sos.status <> 'active' THEN
    -- Truy vấn nhanh ai là người vừa resolve sự kiện này trong alarm_logs
    SELECT performer_name, created_at 
    INTO v_last_resolver_name, v_last_resolved_at
    FROM public.alarm_logs
    WHERE sos_event_id = p_sos_event_id AND action = 'RESOLVE'
    ORDER BY created_at DESC LIMIT 1;

    RETURN jsonb_build_object(
      'success', false,
      'error', 'CONFLICT_ALREADY_RESOLVED',
      'message', 'Báo động này đã được xử lý bởi ' || COALESCE(v_last_resolver_name, 'thành viên khác trong gia đình') || '.',
      'resolved_by_name', COALESCE(v_last_resolver_name, 'Người thân'),
      'resolved_at', v_last_resolved_at
    );
  END IF;

  -- 7. CẬP NHẬT NGUYÊN TỬ: Chuyển status sos_events sang 'resolved'
  UPDATE public.sos_events
  SET status = 'resolved',
      resolved_at = NOW(),
      resolved_by = v_caller_id,
      resolution_note = p_note
  WHERE id = v_target_sos.id;

  -- 8. Phản chiếu trạng thái checkin_logs hôm nay về 'Safe'
  IF v_pairing_code IS NOT NULL THEN
    UPDATE public.checkin_logs
    SET status = 'Safe'
    WHERE family_code = v_pairing_code AND log_date = CURRENT_DATE;
  END IF;

  -- 9. GHI AUDIT TRAIL TRONG CÙNG TRANSACTION (Tuyệt đối không lưu pairing_code)
  INSERT INTO public.alarm_logs (
    elderly_id, sos_event_id, action,
    performed_by, performer_name, performer_role,
    previous_state, new_state, note
  ) VALUES (
    p_elderly_id, v_target_sos.id, 'RESOLVE',
    v_caller_id, COALESCE(v_caller_name, 'Người thân'), COALESCE(v_caller_role, 'caregiver'),
    'active', 'resolved', p_note
  );

  RETURN jsonb_build_object(
    'success', true,
    'message', 'Đã tắt báo động, xác nhận an toàn thành công',
    'sos_event_id', v_target_sos.id,
    'resolved_by', v_caller_name,
    'resolved_at', NOW()
  );
END;
$$;

-- 5. RPC FUNCTION: request_ping_atomic
-- Khóa hàng trên bảng profiles của Cụ để serialize các request Ping đồng thời
CREATE OR REPLACE FUNCTION public.request_ping_atomic(
  p_elderly_id UUID
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_caller_id UUID := auth.uid();
  v_caller_name VARCHAR(100);
  v_caller_email VARCHAR;
  v_pairing_code VARCHAR;
  v_last_ping TIMESTAMPTZ;
  v_cooldown_interval INTERVAL := INTERVAL '15 minutes';
  v_last_pinger_name VARCHAR;
  v_diff_seconds INT;
  v_locked_elderly_id UUID;
BEGIN
  -- 1. Bảo mật: Chặn Anonymous Caller
  IF v_caller_id IS NULL THEN
    RAISE EXCEPTION 'Unauthorized: Yêu cầu đăng nhập để gửi chuông kiểm tra' USING ERRCODE = '42501';
  END IF;

  -- 2. Kiểm tra quan hệ gia đình (chỉ Caregiver có liên kết accepted)
  IF NOT EXISTS (
    SELECT 1 FROM public.family_links
    WHERE elderly_id = p_elderly_id 
      AND caregiver_id = v_caller_id 
      AND status = 'accepted'
  ) THEN
    RAISE EXCEPTION 'Forbidden: Bạn không có quyền gửi chuông cho Cụ này' USING ERRCODE = '42501';
  END IF;

  -- 3. KHÓA ROW PROFILES CỦA CỤ (Đối tượng đảm bảo luôn tồn tại 100% trong DB)
  SELECT id, pairing_code INTO v_locked_elderly_id, v_pairing_code
  FROM public.profiles
  WHERE id = p_elderly_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'NOT_FOUND', 'message', 'Không tìm thấy hồ sơ của Cụ');
  END IF;

  -- Lấy thông tin người gọi
  SELECT full_name, email INTO v_caller_name, v_caller_email FROM public.profiles WHERE id = v_caller_id;

  -- Hỗ trợ tài khoản tester: Cooldown rút ngắn còn 10 giây
  IF LOWER(COALESCE(v_caller_email, '')) = 'test01@gmail.com' THEN
    v_cooldown_interval := INTERVAL '10 seconds';
  END IF;

  -- 4. Kiểm tra thời điểm Ping gần nhất từ checkin_logs
  SELECT ping_requested_at INTO v_last_ping
  FROM public.checkin_logs
  WHERE family_code = v_pairing_code AND log_date = CURRENT_DATE;

  -- 5. Nếu đang trong Cooldown -> Báo lỗi xung đột ngay lập tức
  IF v_last_ping IS NOT NULL AND (NOW() - v_last_ping) < v_cooldown_interval THEN
    v_diff_seconds := EXTRACT(EPOCH FROM (NOW() - v_last_ping))::INT;
    
    SELECT performer_name INTO v_last_pinger_name
    FROM public.alarm_logs
    WHERE elderly_id = p_elderly_id AND action = 'PING'
    ORDER BY created_at DESC LIMIT 1;

    RETURN jsonb_build_object(
      'success', false,
      'error', 'CONFLICT_PING_ALREADY_SENT',
      'message', 'Chuông kiểm tra vừa được gửi bởi ' || COALESCE(v_last_pinger_name, 'thành viên khác') || ' cách đây ' || v_diff_seconds || ' giây.',
      'last_pinger_name', COALESCE(v_last_pinger_name, 'Người thân'),
      'remaining_seconds', EXTRACT(EPOCH FROM (v_cooldown_interval - (NOW() - v_last_ping)))::INT
    );
  END IF;

  -- 6. Cập nhật hoặc tạo mới bản ghi checkin_logs ngày hôm nay
  INSERT INTO public.checkin_logs (family_code, log_date, status, ping_requested_at, elderly_id)
  VALUES (v_pairing_code, CURRENT_DATE, 'Ping_Requested', NOW(), p_elderly_id)
  ON CONFLICT (family_code, log_date)
  DO UPDATE SET status = 'Ping_Requested', ping_requested_at = NOW();

  -- 7. Ghi Audit Log vào alarm_logs (Không lưu pairing_code)
  INSERT INTO public.alarm_logs (
    elderly_id, action, performed_by, performer_name, performer_role, new_state
  ) VALUES (
    p_elderly_id, 'PING', v_caller_id, COALESCE(v_caller_name, 'Người thân'), 'caregiver', 'Ping_Requested'
  );

  RETURN jsonb_build_object(
    'success', true,
    'message', 'Đã phát chuông kiểm tra tới máy Cụ'
  );
END;
$$;

-- 6. SIẾT CHẶT PHÂN QUYỀN THỰC THI (DEFENSE-IN-DEPTH)
REVOKE EXECUTE ON FUNCTION public.create_sos_event_idempotent(UUID, UUID, TEXT) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.resolve_alarm_atomic(UUID, UUID, TEXT) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.request_ping_atomic(UUID) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.create_sos_event_idempotent(UUID, UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.resolve_alarm_atomic(UUID, UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.request_ping_atomic(UUID) TO authenticated;


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- MIGRATION: 20260912000000_custom_checkin_schedule.sql
-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

-- ====================================================================
-- SafeCheck - Migration v4.0: Custom Check-in Schedule & Dynamic Engine
-- PRD: PRD_CHECKIN_SCHEDULE.md (v1.2)
-- ====================================================================

-- 1. BẢNG CẤU HÌNH LỊCH ĐIỂM DANH THEO TỪNG CỤ
CREATE TABLE IF NOT EXISTS public.checkin_schedules (
  elderly_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  checkin_start TIME NOT NULL DEFAULT '07:00:00',
  checkin_deadline TIME NOT NULL DEFAULT '09:00:00',
  emergency_buffer_minutes INT NOT NULL DEFAULT 30,
  timezone VARCHAR(50) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  updated_by UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),

  -- Bất biến 2, 7 & 9: Ràng buộc múi giờ & Không tràn ngày qua Epoch (< 86400s)
  CONSTRAINT check_timezone_vn CHECK (timezone = 'Asia/Ho_Chi_Minh'),
  CONSTRAINT check_start_before_deadline CHECK (checkin_start < checkin_deadline),
  CONSTRAINT check_valid_buffer CHECK (emergency_buffer_minutes BETWEEN 5 AND 120),
  CONSTRAINT check_no_day_overflow CHECK (
    (EXTRACT(EPOCH FROM checkin_deadline) + (emergency_buffer_minutes * 60)) < 86400
  )
);

CREATE INDEX IF NOT EXISTS idx_checkin_schedules_active 
ON public.checkin_schedules(elderly_id) WHERE is_active = TRUE;

-- Đăng ký Realtime publication cho checkin_schedules
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'checkin_schedules'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.checkin_schedules;
  END IF;
END $$;


-- 2. MỞ RỘNG BẢNG CHECKIN_LOGS CHO HISTORY & SNAPSHOTTING
ALTER TABLE public.checkin_logs 
ADD COLUMN IF NOT EXISTS scheduled_start TIME DEFAULT '07:00:00',
ADD COLUMN IF NOT EXISTS scheduled_deadline TIME DEFAULT '09:00:00',
ADD COLUMN IF NOT EXISTS buffer_minutes INT DEFAULT 30,
ADD COLUMN IF NOT EXISTS emergency_reason VARCHAR(30),
ADD COLUMN IF NOT EXISTS emergency_triggered_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS resolved_by UUID REFERENCES public.profiles(id),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- Đảm bảo check constraint emergency_reason hợp lệ nếu chưa có
DO $$ BEGIN
  ALTER TABLE public.checkin_logs 
  ADD CONSTRAINT check_emergency_reason 
  CHECK (emergency_reason IS NULL OR emergency_reason IN ('TIMEOUT', 'SOS', 'OVERDUE_PING'));
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

-- Đảm bảo có Unique Constraint (elderly_id, log_date) phục vụ ON CONFLICT
DO $$ BEGIN
  UPDATE public.checkin_logs l
  SET elderly_id = p.id
  FROM public.profiles p
  WHERE l.elderly_id IS NULL AND l.family_code = p.pairing_code;

  DELETE FROM public.checkin_logs WHERE elderly_id IS NULL;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'unique_elderly_date'
  ) THEN
    ALTER TABLE public.checkin_logs ADD CONSTRAINT unique_elderly_date UNIQUE (elderly_id, log_date);
  END IF;
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

-- Đảm bảo checkin_logs nằm trong Supabase Realtime
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'checkin_logs'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.checkin_logs;
  END IF;
END $$;

-- Bất biến 3: Trigger bảo vệ Snapshot Immutability ở tầng DB
CREATE OR REPLACE FUNCTION public.enforce_checkin_log_immutability()
RETURNS TRIGGER 
LANGUAGE plpgsql
AS $$
BEGIN
  -- 1. Cấm sửa đổi dữ liệu điểm danh của log quá khứ
  IF OLD.log_date < (now() AT TIME ZONE 'Asia/Ho_Chi_Minh')::DATE THEN
    IF NEW.status IS DISTINCT FROM OLD.status
       OR NEW.checkin_time IS DISTINCT FROM OLD.checkin_time
       OR NEW.scheduled_start IS DISTINCT FROM OLD.scheduled_start
       OR NEW.scheduled_deadline IS DISTINCT FROM OLD.scheduled_deadline
       OR NEW.buffer_minutes IS DISTINCT FROM OLD.buffer_minutes THEN
      RAISE EXCEPTION 'Bảo mật: Bản ghi điểm danh quá khứ là bất biến tuyệt đối (Immutable)!';
    END IF;
  END IF;

  -- 2. Đối với log hôm nay, nếu đã đạt Safe hoặc Emergency, cấm đổi snapshot mốc giờ
  IF OLD.status IN ('Safe', 'Emergency') THEN
    IF NEW.scheduled_start IS DISTINCT FROM OLD.scheduled_start
       OR NEW.scheduled_deadline IS DISTINCT FROM OLD.scheduled_deadline
       OR NEW.buffer_minutes IS DISTINCT FROM OLD.buffer_minutes THEN
      RAISE EXCEPTION 'Bảo mật: Không được phép thay đổi mốc giờ snapshot khi ngày đã Safe hoặc Emergency!';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_enforce_checkin_log_immutability ON public.checkin_logs;
CREATE TRIGGER tr_enforce_checkin_log_immutability
BEFORE UPDATE ON public.checkin_logs
FOR EACH ROW EXECUTE FUNCTION public.enforce_checkin_log_immutability();


-- 3. CỦNG CỐ ROW LEVEL SECURITY (RLS)

-- 3.1. RLS cho checkin_schedules (Chặn DELETE hoàn toàn)
ALTER TABLE public.checkin_schedules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Elderly and Caregivers view schedule" ON public.checkin_schedules;
CREATE POLICY "Elderly and Caregivers view schedule"
ON public.checkin_schedules FOR SELECT
USING (
  auth.uid() = elderly_id 
  OR EXISTS (
    SELECT 1 FROM public.family_links fl
    WHERE fl.elderly_id = checkin_schedules.elderly_id
      AND fl.caregiver_id = auth.uid()
      AND fl.status = 'accepted'
  )
);

DROP POLICY IF EXISTS "Caregivers insert linked elderly schedule" ON public.checkin_schedules;
CREATE POLICY "Caregivers insert linked elderly schedule"
ON public.checkin_schedules FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.family_links fl
    WHERE fl.elderly_id = checkin_schedules.elderly_id
      AND fl.caregiver_id = auth.uid()
      AND fl.status = 'accepted'
  )
);

DROP POLICY IF EXISTS "Caregivers update linked elderly schedule" ON public.checkin_schedules;
CREATE POLICY "Caregivers update linked elderly schedule"
ON public.checkin_schedules FOR UPDATE
USING (
  EXISTS (
    SELECT 1 FROM public.family_links fl
    WHERE fl.elderly_id = checkin_schedules.elderly_id
      AND fl.caregiver_id = auth.uid()
      AND fl.status = 'accepted'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.family_links fl
    WHERE fl.elderly_id = checkin_schedules.elderly_id
      AND fl.caregiver_id = auth.uid()
      AND fl.status = 'accepted'
  )
);
-- KHÔNG CÓ POLICY DELETE CHO checkin_schedules (Bất biến 8)

-- 3.2. Audit RLS trên checkin_logs: Cấm direct mutations từ client
ALTER TABLE public.checkin_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Elderly insert own checkin logs" ON public.checkin_logs;
DROP POLICY IF EXISTS "Elderly update own checkin logs" ON public.checkin_logs;
DROP POLICY IF EXISTS "Caregivers update linked elderly checkin logs" ON public.checkin_logs;
DROP POLICY IF EXISTS "Caregivers insert linked elderly checkin logs" ON public.checkin_logs;
DROP POLICY IF EXISTS "Elderly delete own checkin logs" ON public.checkin_logs;
DROP POLICY IF EXISTS "Caregivers delete linked elderly checkin logs" ON public.checkin_logs;

DROP POLICY IF EXISTS "Elderly view own checkin logs" ON public.checkin_logs;
CREATE POLICY "Elderly view own checkin logs"
ON public.checkin_logs FOR SELECT
USING (auth.uid() = elderly_id);

DROP POLICY IF EXISTS "Caregivers view linked elderly checkin logs" ON public.checkin_logs;
CREATE POLICY "Caregivers view linked elderly checkin logs"
ON public.checkin_logs FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.family_links fl
    WHERE fl.elderly_id = checkin_logs.elderly_id
      AND fl.caregiver_id = auth.uid()
      AND fl.status = 'accepted'
  )
);


-- 4. CÁC HÀM XỬ LÝ NGHIỆP VỤ (SECURITY DEFINER RPCs)

-- 4.1. Hàm cập nhật cấu hình khung giờ: update_checkin_schedule
CREATE OR REPLACE FUNCTION public.update_checkin_schedule(
  p_elderly_id UUID,
  p_start TIME,
  p_deadline TIME,
  p_buffer_minutes INT DEFAULT 30
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_caller_id UUID := auth.uid();
  v_is_authorized BOOLEAN := FALSE;
  v_today DATE;
  v_today_log RECORD;
  v_current_local_time TIME;
  v_new_status VARCHAR;
BEGIN
  -- 1. Kiểm tra xác thực
  IF v_caller_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'UNAUTHORIZED', 'message', 'Yêu cầu đăng nhập');
  END IF;

  -- 2. Kiểm tra quyền Caregiver đã kết nối hợp lệ
  SELECT TRUE INTO v_is_authorized
  FROM public.family_links
  WHERE elderly_id = p_elderly_id
    AND caregiver_id = v_caller_id
    AND status = 'accepted';

  IF NOT FOUND OR v_is_authorized IS NOT TRUE THEN
    RETURN jsonb_build_object('success', false, 'error', 'FORBIDDEN', 'message', 'Chỉ người thân đã kết nối mới có quyền đổi giờ');
  END IF;

  -- 3. Kiểm tra tính hợp lệ của thời gian (Bất biến 2)
  IF p_start >= p_deadline THEN
    RETURN jsonb_build_object('success', false, 'error', 'INVALID_RANGE', 'message', 'Giờ bắt đầu phải trước giờ hạn chót');
  END IF;

  IF p_buffer_minutes < 5 OR p_buffer_minutes > 120 THEN
    RETURN jsonb_build_object('success', false, 'error', 'INVALID_BUFFER', 'message', 'Thời gian chờ phải từ 5 đến 120 phút');
  END IF;

  IF (EXTRACT(EPOCH FROM p_deadline) + (p_buffer_minutes * 60)) >= 86400 THEN
    RETURN jsonb_build_object('success', false, 'error', 'DAY_OVERFLOW', 'message', 'Hạn chót cộng thời gian chờ không được vượt quá 23:59 trong ngày');
  END IF;

  -- 4. Ghi đè hoặc tạo mới cấu hình
  INSERT INTO public.checkin_schedules (
    elderly_id, checkin_start, checkin_deadline, emergency_buffer_minutes, timezone, updated_by, updated_at
  )
  VALUES (
    p_elderly_id, p_start, p_deadline, p_buffer_minutes, 'Asia/Ho_Chi_Minh', v_caller_id, now()
  )
  ON CONFLICT (elderly_id) DO UPDATE
  SET checkin_start = EXCLUDED.checkin_start,
      checkin_deadline = EXCLUDED.checkin_deadline,
      emergency_buffer_minutes = EXCLUDED.emergency_buffer_minutes,
      updated_by = EXCLUDED.updated_by,
      updated_at = now();

  -- 5. Xử lý tác động tức thì tới bản ghi hôm nay (Bất biến 3)
  v_today := (now() AT TIME ZONE 'Asia/Ho_Chi_Minh')::DATE;
  v_current_local_time := (now() AT TIME ZONE 'Asia/Ho_Chi_Minh')::TIME;

  SELECT * INTO v_today_log
  FROM public.checkin_logs
  WHERE elderly_id = p_elderly_id AND log_date = v_today;

  IF FOUND THEN
    -- Nếu Cụ ĐÃ Safe hoặc ĐANG trong báo động Emergency -> Snapshot IMMUTABLE!
    IF v_today_log.status NOT IN ('Safe', 'Emergency') THEN
      IF v_current_local_time < p_start THEN
        v_new_status := 'Early_Waiting';
      ELSIF v_current_local_time <= p_deadline THEN
        v_new_status := 'Waiting';
      ELSIF v_current_local_time <= (p_deadline + (p_buffer_minutes || ' minutes')::INTERVAL) THEN
        v_new_status := 'Late';
      ELSE
        v_new_status := 'Emergency';
      END IF;

      UPDATE public.checkin_logs
      SET scheduled_start = p_start,
          scheduled_deadline = p_deadline,
          buffer_minutes = p_buffer_minutes,
          status = v_new_status,
          emergency_reason = CASE WHEN v_new_status = 'Emergency' THEN 'TIMEOUT' ELSE emergency_reason END,
          emergency_triggered_at = CASE WHEN v_new_status = 'Emergency' THEN now() ELSE emergency_triggered_at END,
          updated_at = now()
      WHERE id = v_today_log.id;
    END IF;
  ELSE
    -- Chưa có bản ghi hôm nay -> Khởi tạo sẵn bản ghi
    IF v_current_local_time < p_start THEN
      v_new_status := 'Early_Waiting';
    ELSIF v_current_local_time <= p_deadline THEN
      v_new_status := 'Waiting';
    ELSE
      v_new_status := 'Late';
    END IF;

    INSERT INTO public.checkin_logs (
      elderly_id, log_date, scheduled_start, scheduled_deadline, buffer_minutes, status
    )
    VALUES (
      p_elderly_id, v_today, p_start, p_deadline, p_buffer_minutes, v_new_status
    )
    ON CONFLICT (elderly_id, log_date) DO NOTHING;
  END IF;

  RETURN jsonb_build_object(
    'success', true, 
    'message', 'Cập nhật khung giờ điểm danh thành công',
    'schedule', jsonb_build_object(
      'checkin_start', p_start,
      'checkin_deadline', p_deadline,
      'emergency_buffer_minutes', p_buffer_minutes
    )
  );
END;
$$;

-- 4.2. Hàm điểm danh hàng ngày: perform_checkin_atomic_v2
CREATE OR REPLACE FUNCTION public.perform_checkin_atomic_v2(
  p_elderly_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_caller_id UUID := auth.uid();
  v_sched RECORD;
  v_today DATE;
  v_server_local_time TIME;
  v_today_log RECORD;
BEGIN
  -- 1. Xác thực caller chính là Cụ
  IF v_caller_id IS NULL OR v_caller_id <> p_elderly_id THEN
    RETURN jsonb_build_object('success', false, 'error', 'UNAUTHORIZED', 'message', 'Chỉ Cụ mới có quyền bấm điểm danh');
  END IF;

  -- 2. Căn cứ thời gian lấy từ SERVER CLOCK (Asia/Ho_Chi_Minh)
  v_today := (now() AT TIME ZONE 'Asia/Ho_Chi_Minh')::DATE;
  v_server_local_time := (now() AT TIME ZONE 'Asia/Ho_Chi_Minh')::TIME;

  -- 3. Đọc cấu hình khung giờ của Cụ (hoặc fallback)
  SELECT * INTO v_sched 
  FROM public.checkin_schedules 
  WHERE elderly_id = p_elderly_id;

  IF NOT FOUND THEN
    v_sched.checkin_start := '07:00:00'::TIME;
    v_sched.checkin_deadline := '09:00:00'::TIME;
    v_sched.emergency_buffer_minutes := 30;
  END IF;

  -- 4. Kiểm tra bản ghi hôm nay
  SELECT * INTO v_today_log
  FROM public.checkin_logs
  WHERE elderly_id = p_elderly_id AND log_date = v_today;

  -- Bất biến 7: Chặn nếu đang trong Emergency
  IF FOUND AND v_today_log.status = 'Emergency' THEN
    RETURN jsonb_build_object(
      'success', false, 
      'error', 'STATE_IN_EMERGENCY', 
      'message', 'Hệ thống đang phát báo động khẩn cấp. Cần người thân xác nhận an toàn hoặc liên hệ hỗ trợ trực tiếp.'
    );
  END IF;

  -- 5. Chặn nếu chưa đến giờ bắt đầu (Server Time)
  IF v_server_local_time < v_sched.checkin_start THEN
    RETURN jsonb_build_object(
      'success', false, 
      'error', 'TOO_EARLY', 
      'message', 'Chưa đến giờ điểm danh. Cụ hãy quay lại sau ' || to_char(v_sched.checkin_start, 'HH24:MI')
    );
  END IF;

  -- 6. Ghi nhận an toàn (Safe)
  INSERT INTO public.checkin_logs (
    elderly_id, log_date, scheduled_start, scheduled_deadline, buffer_minutes, 
    status, checkin_time, source
  )
  VALUES (
    p_elderly_id, v_today, v_sched.checkin_start, v_sched.checkin_deadline, v_sched.emergency_buffer_minutes,
    'Safe', now(), 'Daily_Button'
  )
  ON CONFLICT (elderly_id, log_date) DO UPDATE
  SET status = 'Safe',
      checkin_time = COALESCE(public.checkin_logs.checkin_time, now()),
      source = COALESCE(public.checkin_logs.source, 'Daily_Button'),
      updated_at = now()
  RETURNING * INTO v_today_log;

  -- 7. Audit trail
  INSERT INTO public.alarm_logs (
    elderly_id, action, performed_by, performer_name, performer_role, note, new_state
  )
  VALUES (
    p_elderly_id, 'CHECKIN_SAFE', p_elderly_id, 'Cụ', 'elderly', 'Điểm danh buổi sáng thành công', 'Safe'
  );

  RETURN jsonb_build_object(
    'success', true, 
    'message', 'Điểm danh an toàn thành công',
    'checkin_time', v_today_log.checkin_time
  );
END;
$$;

-- 4.3. Cập nhật create_sos_event_idempotent phản chiếu emergency_reason = 'SOS'
DROP FUNCTION IF EXISTS public.create_sos_event_idempotent(UUID, UUID, VARCHAR);

CREATE OR REPLACE FUNCTION public.create_sos_event_idempotent(
  p_elderly_id UUID,
  p_client_event_id UUID,
  p_trigger_source TEXT DEFAULT 'button'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_caller_id UUID := auth.uid();
  v_is_authorized BOOLEAN := FALSE;
  v_existing_event RECORD;
  v_new_event RECORD;
  v_pairing_code VARCHAR;
  v_caller_name VARCHAR;
  v_caller_role VARCHAR;
  v_today DATE := (now() AT TIME ZONE 'Asia/Ho_Chi_Minh')::DATE;
BEGIN
  IF v_caller_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'UNAUTHORIZED', 'message', 'Yêu cầu đăng nhập');
  END IF;

  IF v_caller_id = p_elderly_id THEN
    v_is_authorized := TRUE;
  ELSE
    SELECT TRUE INTO v_is_authorized
    FROM public.family_links
    WHERE elderly_id = p_elderly_id
      AND caregiver_id = v_caller_id
      AND status = 'accepted';
  END IF;

  IF NOT FOUND OR v_is_authorized IS NOT TRUE THEN
    RETURN jsonb_build_object('success', false, 'error', 'FORBIDDEN', 'message', 'Không có quyền kích hoạt SOS cho Cụ này');
  END IF;

  SELECT * INTO v_existing_event
  FROM public.sos_events
  WHERE client_event_id = p_client_event_id;

  IF FOUND THEN
    RETURN jsonb_build_object(
      'success', true,
      'sos_event_id', v_existing_event.id,
      'status', v_existing_event.status,
      'is_duplicate', true,
      'message', 'Sự kiện đã được ghi nhận trước đó (Idempotent ACK)'
    );
  END IF;

  INSERT INTO public.sos_events (
    client_event_id, elderly_id, triggered_by, trigger_source, status
  )
  VALUES (
    p_client_event_id, p_elderly_id, v_caller_id, p_trigger_source, 'active'
  )
  ON CONFLICT (client_event_id) DO NOTHING
  RETURNING * INTO v_new_event;

  IF v_new_event.id IS NULL THEN
    SELECT * INTO v_existing_event
    FROM public.sos_events
    WHERE client_event_id = p_client_event_id;

    RETURN jsonb_build_object(
      'success', true,
      'sos_event_id', v_existing_event.id,
      'status', v_existing_event.status,
      'is_duplicate', true,
      'message', 'Sự kiện đã được ghi nhận trước đó (Idempotent ACK)'
    );
  END IF;

  SELECT pairing_code INTO v_pairing_code FROM public.profiles WHERE id = p_elderly_id;
  SELECT full_name, role INTO v_caller_name, v_caller_role FROM public.profiles WHERE id = v_caller_id;

  -- Phản chiếu trạng thái sang checkin_logs hôm nay kèm emergency_reason = 'SOS'
  INSERT INTO public.checkin_logs (
    elderly_id, family_code, log_date, status, source, emergency_reason, emergency_triggered_at
  )
  VALUES (
    p_elderly_id, v_pairing_code, v_today, 'Emergency', 'SOS', 'SOS', now()
  )
  ON CONFLICT (elderly_id, log_date)
  DO UPDATE SET status = 'Emergency', 
                source = 'SOS', 
                emergency_reason = 'SOS', 
                emergency_triggered_at = COALESCE(public.checkin_logs.emergency_triggered_at, now()),
                updated_at = now();

  INSERT INTO public.alarm_logs (
    elderly_id, sos_event_id, action,
    performed_by, performer_name, performer_role, new_state
  ) VALUES (
    p_elderly_id, v_new_event.id, 'SOS_TRIGGERED',
    v_caller_id, COALESCE(v_caller_name, 'Người dùng'), COALESCE(v_caller_role, 'elderly'), 'Emergency'
  );

  RETURN jsonb_build_object(
    'success', true,
    'sos_event_id', v_new_event.id,
    'status', v_new_event.status,
    'is_duplicate', false,
    'message', 'Đã kích hoạt báo động khẩn cấp SOS'
  );
END;
$$;

-- 4.4. Cập nhật resolve_alarm_atomic phản chiếu resolved_at, resolved_by
CREATE OR REPLACE FUNCTION public.resolve_alarm_atomic(
  p_elderly_id UUID,
  p_sos_event_id UUID,
  p_note TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_caller_id UUID := auth.uid();
  v_is_authorized BOOLEAN := FALSE;
  v_target_sos RECORD;
  v_pairing_code VARCHAR;
  v_caller_name VARCHAR;
  v_caller_role VARCHAR;
  v_today DATE := (now() AT TIME ZONE 'Asia/Ho_Chi_Minh')::DATE;
BEGIN
  IF v_caller_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'UNAUTHORIZED', 'message', 'Yêu cầu đăng nhập');
  END IF;

  SELECT TRUE INTO v_is_authorized
  FROM public.family_links
  WHERE elderly_id = p_elderly_id
    AND caregiver_id = v_caller_id
    AND status = 'accepted';

  IF NOT FOUND OR v_is_authorized IS NOT TRUE THEN
    RETURN jsonb_build_object('success', false, 'error', 'FORBIDDEN', 'message', 'Chỉ người thân đã kết nối mới có quyền tắt báo động');
  END IF;

  SELECT * INTO v_target_sos
  FROM public.sos_events
  WHERE id = p_sos_event_id AND elderly_id = p_elderly_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'EVENT_NOT_FOUND', 'message', 'Không tìm thấy sự kiện báo động');
  END IF;

  IF v_target_sos.status = 'resolved' THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'CONFLICT_ALREADY_RESOLVED',
      'message', 'Báo động này đã được giải quyết trước đó',
      'resolved_by', v_target_sos.resolved_by,
      'resolved_at', v_target_sos.resolved_at
    );
  END IF;

  SELECT pairing_code INTO v_pairing_code FROM public.profiles WHERE id = p_elderly_id;
  SELECT full_name, role INTO v_caller_name, v_caller_role FROM public.profiles WHERE id = v_caller_id;

  UPDATE public.sos_events
  SET status = 'resolved',
      resolved_at = now(),
      resolved_by = v_caller_id,
      resolution_note = p_note
  WHERE id = v_target_sos.id;

  -- Phản chiếu trạng thái checkin_logs hôm nay về 'Safe' và lưu resolved metadata
  UPDATE public.checkin_logs
  SET status = 'Safe',
      resolved_at = now(),
      resolved_by = v_caller_id,
      updated_at = now()
  WHERE elderly_id = p_elderly_id AND log_date = v_today;

  INSERT INTO public.alarm_logs (
    elderly_id, sos_event_id, action,
    performed_by, performer_name, performer_role,
    previous_state, new_state, note
  ) VALUES (
    p_elderly_id, v_target_sos.id, 'RESOLVE',
    v_caller_id, COALESCE(v_caller_name, 'Người thân'), COALESCE(v_caller_role, 'caregiver'),
    'active', 'resolved', p_note
  );

  RETURN jsonb_build_object(
    'success', true,
    'message', 'Đã tắt báo động thành công',
    'sos_event_id', v_target_sos.id,
    'resolved_by', v_caller_id,
    'resolved_by_name', COALESCE(v_caller_name, 'Người thân'),
    'resolved_at', now()
  );
END;
$$;

-- 4.5. Dynamic Cron Engine: check_overdue_routine_v2
CREATE OR REPLACE FUNCTION public.check_overdue_routine_v2()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_today DATE := (now() AT TIME ZONE 'Asia/Ho_Chi_Minh')::DATE;
  v_current_time TIME := (now() AT TIME ZONE 'Asia/Ho_Chi_Minh')::TIME;
BEGIN
  -- BƯỚC 0: MATERIALIZE TODAY'S LOGS CHO MỌI CỤ (Bất biến 1)
  INSERT INTO public.checkin_logs (
    elderly_id, log_date, scheduled_start, scheduled_deadline, buffer_minutes, status
  )
  SELECT 
    p.id,
    v_today,
    COALESCE(s.checkin_start, '07:00:00'::TIME),
    COALESCE(s.checkin_deadline, '09:00:00'::TIME),
    COALESCE(s.emergency_buffer_minutes, 30),
    CASE 
      WHEN v_current_time < COALESCE(s.checkin_start, '07:00:00'::TIME) THEN 'Early_Waiting'
      WHEN v_current_time <= COALESCE(s.checkin_deadline, '09:00:00'::TIME) THEN 'Waiting'
      WHEN v_current_time <= (COALESCE(s.checkin_deadline, '09:00:00'::TIME) + (COALESCE(s.emergency_buffer_minutes, 30) || ' minutes')::INTERVAL) THEN 'Late'
      ELSE 'Emergency'
    END
  FROM public.profiles p
  LEFT JOIN public.checkin_schedules s ON p.id = s.elderly_id AND s.is_active = TRUE
  WHERE p.role = 'elderly'
  ON CONFLICT (elderly_id, log_date) DO NOTHING;

  -- 1. Chuyển Early_Waiting -> Waiting khi đến giờ checkin_start
  UPDATE public.checkin_logs l
  SET status = 'Waiting', updated_at = now()
  WHERE l.log_date = v_today
    AND l.status = 'Early_Waiting'
    AND v_current_time >= l.scheduled_start;

  -- 2. Chuyển Waiting -> Late khi quá checkin_deadline
  UPDATE public.checkin_logs l
  SET status = 'Late', updated_at = now()
  WHERE l.log_date = v_today
    AND l.status = 'Waiting'
    AND v_current_time > l.scheduled_deadline;

  -- 3. Chuyển Late -> Emergency khi quá buffer_minutes (Lưu emergency_reason = 'TIMEOUT')
  UPDATE public.checkin_logs l
  SET status = 'Emergency', 
      emergency_reason = 'TIMEOUT',
      emergency_triggered_at = now(),
      source = 'TIMEOUT', 
      updated_at = now()
  WHERE l.log_date = v_today
    AND l.status = 'Late'
    AND v_current_time > (l.scheduled_deadline + (l.buffer_minutes || ' minutes')::INTERVAL);

  -- 4. Quá 15 phút từ lúc Ping mà Cụ chưa phản hồi -> Chuyển thành Overdue_Ping
  UPDATE public.checkin_logs
  SET status = 'Overdue_Ping', 
      emergency_reason = 'OVERDUE_PING',
      emergency_triggered_at = now(),
      updated_at = now()
  WHERE log_date = v_today
    AND status = 'Ping_Requested'
    AND (now() - ping_requested_at) > INTERVAL '15 minutes';
END;
$$;

-- 5. CẬP NHẬT PG_CRON SCHEDULE
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'auto-detect-late-elderly') THEN
      PERFORM cron.unschedule('auto-detect-late-elderly');
    END IF;

    PERFORM cron.schedule(
      'auto-detect-late-elderly',
      '* * * * *',
      'SELECT public.check_overdue_routine_v2()'
    );
  END IF;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'pg_cron không khả dụng hoặc quyền hạn bị giới hạn: %', SQLERRM;
END $$;

