-- ====================================================================
-- SafeCheck - Migration v1.0: Core Schema, RPC Functions & Cron Jobs
-- ====================================================================

-- 1. Bật Extensions cần thiết
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- 2. Đảm bảo cấu trúc các bảng
CREATE TABLE IF NOT EXISTS configurations (
  family_code VARCHAR PRIMARY KEY,
  checkin_start TIME NOT NULL DEFAULT '07:00:00',
  checkin_deadline TIME NOT NULL DEFAULT '09:00:00',
  emergency_buffer_minutes INT NOT NULL DEFAULT 30,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS checkin_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_code VARCHAR NOT NULL,
  log_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status VARCHAR NOT NULL DEFAULT 'Waiting',
  checkin_time TIMESTAMPTZ,
  source VARCHAR,
  ping_requested_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT unique_family_date UNIQUE (family_code, log_date)
);

-- Thêm cột ping_requested_at nếu bảng đã tồn tại từ trước
ALTER TABLE checkin_logs 
ADD COLUMN IF NOT EXISTS ping_requested_at TIMESTAMPTZ;

-- --------------------------------------------------------------------
-- 3. CÁC HÀM BACKEND RPC (Business Logic)
-- --------------------------------------------------------------------

-- 3.1. Điểm danh hàng ngày (Flow 1 & Flow 4)
CREATE OR REPLACE FUNCTION perform_checkin(p_family_code VARCHAR)
RETURNS JSON AS $$
DECLARE
  v_current_time TIME := CURRENT_TIME;
  v_cfg RECORD;
BEGIN
  SELECT * INTO v_cfg FROM configurations WHERE family_code = p_family_code;
  
  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'message', 'Mã gia đình không tồn tại');
  END IF;

  IF v_current_time < v_cfg.checkin_start THEN
    RETURN json_build_object('success', false, 'message', 'Chưa đến khung giờ điểm danh');
  END IF;

  UPDATE checkin_logs
  SET status = 'Safe',
      checkin_time = now(),
      source = 'Daily_Button'
  WHERE family_code = p_family_code 
    AND log_date = CURRENT_DATE;

  RETURN json_build_object('success', true, 'message', 'Điểm danh an toàn thành công');
END;
$$ LANGUAGE plpgsql;

-- 3.2. Con cháu gửi yêu cầu chuông kiểm tra (Flow 4)
CREATE OR REPLACE FUNCTION request_ping(p_family_code VARCHAR)
RETURNS JSON AS $$
DECLARE
  v_last_ping TIMESTAMPTZ;
BEGIN
  SELECT ping_requested_at INTO v_last_ping
  FROM checkin_logs
  WHERE family_code = p_family_code AND log_date = CURRENT_DATE;

  IF v_last_ping IS NOT NULL AND (now() - v_last_ping) < INTERVAL '15 minutes' THEN
    RETURN json_build_object(
      'success', false, 
      'message', 'Đang trong thời gian chờ (cooldown 15 phút)'
    );
  END IF;

  UPDATE checkin_logs
  SET status = 'Ping_Requested',
      ping_requested_at = now()
  WHERE family_code = p_family_code AND log_date = CURRENT_DATE;

  RETURN json_build_object('success', true, 'message', 'Đã phát chuông kiểm tra tới máy Cụ');
END;
$$ LANGUAGE plpgsql;

-- 3.3. Kích hoạt khẩn cấp SOS (Flow 3)
CREATE OR REPLACE FUNCTION trigger_sos(p_family_code VARCHAR)
RETURNS JSON AS $$
BEGIN
  UPDATE checkin_logs
  SET status = 'Emergency',
      source = 'SOS'
  WHERE family_code = p_family_code AND log_date = CURRENT_DATE;

  RETURN json_build_object('success', true, 'message', 'Đã kích hoạt báo động khẩn cấp');
END;
$$ LANGUAGE plpgsql;

-- 3.4. Con cháu tắt báo động / Xác nhận an toàn (Flow 5)
CREATE OR REPLACE FUNCTION resolve_alarm(p_family_code VARCHAR)
RETURNS JSON AS $$
BEGIN
  UPDATE checkin_logs
  SET status = 'Safe'
  WHERE family_code = p_family_code AND log_date = CURRENT_DATE;

  RETURN json_build_object('success', true, 'message', 'Đã tắt báo động, xác nhận an toàn');
END;
$$ LANGUAGE plpgsql;

-- --------------------------------------------------------------------
-- 4. CÁC HÀM QUÉT ĐỊNH KỲ (Lập lịch với pg_cron)
-- --------------------------------------------------------------------

-- 4.1. Hàm quét trễ giờ, quá hạn, overdue ping
CREATE OR REPLACE FUNCTION check_overdue_routine()
RETURNS VOID AS $$
BEGIN
  -- Quá hạn chốt mà vẫn Waiting -> Chuyển thành Late
  UPDATE checkin_logs log
  SET status = 'Late'
  FROM configurations cfg
  WHERE log.family_code = cfg.family_code
    AND log.log_date = CURRENT_DATE
    AND log.status = 'Waiting'
    AND CURRENT_TIME > cfg.checkin_deadline;

  -- Quá hạn buffer phút sau Late -> Chuyển thành Emergency
  UPDATE checkin_logs log
  SET status = 'Emergency'
  FROM configurations cfg
  WHERE log.family_code = cfg.family_code
    AND log.log_date = CURRENT_DATE
    AND log.status = 'Late'
    AND CURRENT_TIME > (cfg.checkin_deadline + (cfg.emergency_buffer_minutes || ' minutes')::INTERVAL);

  -- Quá 15 phút từ lúc Ping mà Cụ chưa phản hồi -> Chuyển thành Overdue_Ping
  UPDATE checkin_logs
  SET status = 'Overdue_Ping'
  WHERE log_date = CURRENT_DATE
    AND status = 'Ping_Requested'
    AND (now() - ping_requested_at) > INTERVAL '15 minutes';
END;
$$ LANGUAGE plpgsql;

-- 4.2. Hàm tự động reset tạo bản ghi ngày mới lúc 00:00
CREATE OR REPLACE FUNCTION reset_daily_routine()
RETURNS VOID AS $$
BEGIN
  INSERT INTO checkin_logs (family_code, log_date, status)
  SELECT family_code, CURRENT_DATE, 'Waiting'
  FROM configurations
  ON CONFLICT (family_code, log_date) DO NOTHING;
END;
$$ LANGUAGE plpgsql;

-- --------------------------------------------------------------------
-- 5. ĐĂNG KÝ LỊCH CRON JOB (Chỉ đăng ký nếu chưa có)
-- --------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'auto-detect-late-elderly') THEN
    PERFORM cron.schedule(
      'auto-detect-late-elderly',
      '* * * * *',
      'SELECT check_overdue_routine()'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'auto-reset-daily') THEN
    PERFORM cron.schedule(
      'auto-reset-daily',
      '0 0 * * *',
      'SELECT reset_daily_routine()'
    );
  END IF;
END $$;
